FROM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
ADD lib/data_registry/requirements.txt /app/requirements_data_registry.txt
RUN pip install -r requirements.txt
RUN pip install -r requirements_data_registry.txt

# Copy libs 
ADD /lib /app/lib/

# Copy service files
ADD /src /app/

# Environment variables
ENV session=

CMD ["sh", "-c", "python knowledge_grounding_agent.py --session ${session}"]
