const {
    faCircleA,
    faServer,
    faHeadSideGear,
    faDatabase,
    faFolderOpen,
    faFile,
    faProjectDiagram,
    faArrowRightToArc,
    faArrowRightFromArc,
    faFunction,
    faCube,
} = require("@fortawesome/pro-duotone-svg-icons");
const { vanillaRenderers } = require("@jsonforms/vanilla-renderers");
import BooleanRenderer, {
    BooleanTester,
} from "@/components/jsonforms/renderers/Boolean";
import ButtonRenderer, {
    ButtonTester,
} from "@/components/jsonforms/renderers/Button";
import EnumRenderer, {
    EnumTester,
} from "@/components/jsonforms/renderers/Enum";
import GroupRenderer, {
    GroupTester,
} from "@/components/jsonforms/renderers/Group";
import IntegerRenderer, {
    IntegerTester,
} from "@/components/jsonforms/renderers/Integer";
import LabelRenderer, {
    LabelTester,
} from "@/components/jsonforms/renderers/Label";
import LayoutRenderer, {
    LayoutTester,
} from "@/components/jsonforms/renderers/Layout";
import NumberRenderer, {
    NumberTester,
} from "@/components/jsonforms/renderers/Number";
import StringRenderer, {
    StringTester,
} from "@/components/jsonforms/renderers/String";
import UnknownRenderer, {
    UnknownTester,
} from "@/components/jsonforms/renderers/Unknown";
import { Classes, Colors, Intent } from "@blueprintjs/core";
import ArrayRenderer, { ArrayTester } from "./jsonforms/renderers/Array";
import DateRenderer, { DateTester } from "./jsonforms/renderers/Date";
import DateTimeRenderer, {
    DateTimeTester,
} from "./jsonforms/renderers/DateTime";
export const REGISTRY_TYPE_LOOKUP = {
        data: { icon: faServer, key: "source" },
        agent: { icon: faCircleA, key: "agent" },
        operator: { icon: faFunction, key: "operator" },
        model: { icon: faCube, key: "model" },
    },
    SEARCH_LIST_TYPE_LOOKUP = {
        agent: { icon: faHeadSideGear },
        input: { icon: faArrowRightToArc },
        output: { icon: faArrowRightFromArc },
        source: { icon: faServer },
        database: { icon: faDatabase },
        collection: { icon: faFolderOpen },
        entity: { icon: faFile },
        relation: { icon: faProjectDiagram },
        model: { icon: faCube },
        operator: { icon: faFunction },
    },
    JSONFORMS_RENDERERS = [
        ...vanillaRenderers,
        { tester: GroupTester, renderer: GroupRenderer },
        { tester: LabelTester, renderer: LabelRenderer },
        { tester: BooleanTester, renderer: BooleanRenderer },
        { tester: EnumTester, renderer: EnumRenderer },
        { tester: LayoutTester, renderer: LayoutRenderer },
        { tester: StringTester, renderer: StringRenderer },
        { tester: NumberTester, renderer: NumberRenderer },
        { tester: IntegerTester, renderer: IntegerRenderer },
        { tester: ButtonTester, renderer: ButtonRenderer },
        { tester: DateTester, renderer: DateRenderer },
        { tester: DateTimeTester, renderer: DateTimeRenderer },
        { tester: ArrayTester, renderer: ArrayRenderer },
        { tester: UnknownTester, renderer: UnknownRenderer },
    ],
    CARD_LIST_CLASS_NAMES = `${Classes.CARD} ${Classes.CARD_LIST} ${Classes.CARD_LIST_BORDERED}`,
    NAVIGATION_MENU_WIDTH = 203,
    CONTAINER_STATUS_INDICATOR = {
        created: { style: { color: Colors.ORANGE5 }, intent: Intent.WARNING },
        running: { style: { color: Colors.GREEN3 }, intent: Intent.SUCCESS },
        paused: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
        restarting: {
            style: { color: Colors.ORANGE5 },
            intent: Intent.WARNING,
        },
        exited: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
        removing: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
        dead: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
    },
    PROFILE_PICTURE_40 = {
        borderRadius: "50%",
        padding: 0,
        overflow: "hidden",
        width: 40,
        height: 40,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    ENTITY_ICON_40 = {
        overflow: "hidden",
        padding: 0,
        width: 40,
        height: 40,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    USER_ROLES_LOOKUP = {
        admin: "Administrator",
        member: "Member",
        guest: "Guest",
        developer: "Developer",
    },
    DEFAULT_ENTITY_ICON = {
        agent: faCircleA,
        data: faDatabase,
        source: faDatabase,
        operator: faFunction,
        model: faCube,
    },
    COLOR_OPTIONS = [
        "#979B9D",
        "#FFA8A8",
        "#FAA2C1",
        "#E599F7",
        "#B197FC",
        "#91A7FF",
        "#74C0FC",
        "#66D9E8",
        "#50514F",
        "#FA5252",
        "#E64980",
        "#BE4BDB",
        "#7950F2",
        "#4C6EF5",
        "#228BE6",
        "#15AABF",
        "#1C2127",
        "#C92A2A",
        "#A61E4D",
        "#862E9C",
        "#5F3DC4",
        "#364FC7",
        "#1864AB",
        "#0B7285",
        "#63E6BE",
        "#8CE99A",
        "#C0EB75",
        "#FFE066",
        "#FFC078",
        "#F1B280",
        "#D3B79E",
        "#C2B9A0",
        "#12B886",
        "#40C057",
        "#82C91E",
        "#FAB005",
        "#FD7E14",
        "#D46E25",
        "#A87C56",
        "#867C65",
        "#087F5B",
        "#2B8A3E",
        "#5C940D",
        "#E67700",
        "#D9480F",
        "#8A4513",
        "#6F4B2D",
        "#4B4639",
    ],
    RESIZE_DIRECTION = { BottomRight: "bottomRight" },
    HEX_TRANSPARENCY = {
        100: "FF",
        99: "FC",
        98: "FA",
        97: "F7",
        96: "F5",
        95: "F2",
        94: "F0",
        93: "ED",
        92: "EB",
        91: "E8",
        90: "E6",
        89: "E3",
        88: "E0",
        87: "DE",
        86: "DB",
        85: "D9",
        84: "D6",
        83: "D4",
        82: "D1",
        81: "CF",
        80: "CC",
        79: "C9",
        78: "C7",
        77: "C4",
        76: "C2",
        75: "BF",
        74: "BD",
        73: "BA",
        72: "B8",
        71: "B5",
        70: "B3",
        69: "B0",
        68: "AD",
        67: "AB",
        66: "A8",
        65: "A6",
        64: "A3",
        63: "A1",
        62: "9E",
        61: "9C",
        60: "99",
        59: "96",
        58: "94",
        57: "91",
        56: "8F",
        55: "8C",
        54: "8A",
        53: "87",
        52: "85",
        51: "82",
        50: "80",
        49: "7D",
        48: "7A",
        47: "78",
        46: "75",
        45: "73",
        44: "70",
        43: "6E",
        42: "6B",
        41: "69",
        40: "66",
        39: "63",
        38: "61",
        37: "5E",
        36: "5C",
        35: "59",
        34: "57",
        33: "54",
        32: "52",
        31: "4F",
        30: "4D",
        29: "4A",
        28: "47",
        27: "45",
        26: "42",
        25: "40",
        24: "3D",
        23: "3B",
        22: "38",
        21: "36",
        20: "33",
        19: "30",
        18: "2E",
        17: "2B",
        16: "29",
        15: "26",
        14: "24",
        13: "21",
        12: "1F",
        11: "1C",
        10: "1A",
        9: "17",
        8: "14",
        7: "12",
        6: "0F",
        5: "0D",
        4: "0A",
        3: "08",
        2: "05",
        1: "03",
        0: "00",
    };
