const {
    faCircleA,
    faServer,
    faHeadSideGear,
    faDatabase,
    faFolderOpen,
    faFile,
    faProjectDiagram,
    faArrowRightToArc,
    faArrowRightFromArc,
} = require("@fortawesome/pro-duotone-svg-icons");
const { vanillaRenderers } = require("@jsonforms/vanilla-renderers");
import BooleanRenderer, {
    BooleanTester,
} from "@/components/jsonforms/renderers/Boolean";
import ButtonRenderer, {
    ButtonTester,
} from "@/components/jsonforms/renderers/Button";
import EnumRenderer, {
    EnumTester,
} from "@/components/jsonforms/renderers/Enum";
import GroupRenderer, {
    GroupTester,
} from "@/components/jsonforms/renderers/Group";
import IntegerRenderer, {
    IntegerTester,
} from "@/components/jsonforms/renderers/Integer";
import LabelRenderer, {
    LabelTester,
} from "@/components/jsonforms/renderers/Label";
import LayoutRenderer, {
    LayoutTester,
} from "@/components/jsonforms/renderers/Layout";
import NumberRenderer, {
    NumberTester,
} from "@/components/jsonforms/renderers/Number";
import StringRenderer, {
    StringTester,
} from "@/components/jsonforms/renderers/String";
import UnknownRenderer, {
    UnknownTester,
} from "@/components/jsonforms/renderers/Unknown";
import { Classes, Colors, Intent } from "@blueprintjs/core";
import ArrayRenderer, { ArrayTester } from "./jsonforms/renderers/Array";
import DateRenderer, { DateTester } from "./jsonforms/renderers/Date";
import DateTimeRenderer, {
    DateTimeTester,
} from "./jsonforms/renderers/DateTime";
module.exports = {
    REGISTRY_TYPE_LOOKUP: {
        data: { icon: faServer, key: "source" },
        agent: { icon: faCircleA, key: "agent" },
    },
    SEARCH_LIST_TYPE_LOOKUP: {
        agent: { icon: faHeadSideGear },
        input: { icon: faArrowRightToArc },
        output: { icon: faArrowRightFromArc },
        source: { icon: faServer },
        database: { icon: faDatabase },
        collection: { icon: faFolderOpen },
        entity: { icon: faFile },
        relation: { icon: faProjectDiagram },
    },
    JSONFORMS_RENDERERS: [
        ...vanillaRenderers,
        { tester: GroupTester, renderer: GroupRenderer },
        { tester: LabelTester, renderer: LabelRenderer },
        { tester: BooleanTester, renderer: BooleanRenderer },
        { tester: EnumTester, renderer: EnumRenderer },
        { tester: LayoutTester, renderer: LayoutRenderer },
        { tester: StringTester, renderer: StringRenderer },
        { tester: NumberTester, renderer: NumberRenderer },
        { tester: IntegerTester, renderer: IntegerRenderer },
        { tester: ButtonTester, renderer: ButtonRenderer },
        { tester: DateTester, renderer: DateRenderer },
        { tester: DateTimeTester, renderer: DateTimeRenderer },
        { tester: ArrayTester, renderer: ArrayRenderer },
        { tester: UnknownTester, renderer: UnknownRenderer },
    ],
    CARD_LIST_CLASS_NAMES: `${Classes.CARD} ${Classes.CARD_LIST} ${Classes.CARD_LIST_BORDERED}`,
    NAVIGATION_MENU_WIDTH: 203,
    CONTAINER_STATUS_INDICATOR: {
        created: { style: { color: Colors.ORANGE5 }, intent: Intent.WARNING },
        running: { style: { color: Colors.GREEN3 }, intent: Intent.SUCCESS },
        paused: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
        restarting: {
            style: { color: Colors.ORANGE5 },
            intent: Intent.WARNING,
        },
        exited: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
        removing: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
        dead: { style: { color: Colors.RED3 }, intent: Intent.DANGER },
    },
    PROFILE_PICTURE_40: {
        borderRadius: "50%",
        padding: 0,
        overflow: "hidden",
        width: 40,
        height: 40,
    },
    ENTITY_ICON_40: {
        overflow: "hidden",
        padding: 0,
        width: 40,
        height: 40,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    USER_ROLES_LOOKUP: {
        admin: "Administrator",
        member: "Member",
        guest: "Guest",
        developer: "Developer",
    },
    COLOR_OPTIONS: [
        "#4D4D4D",
        "#999999",
        "#FFFFFF",
        "#F44E3B",
        "#FE9200",
        "#FCDC00",
        "#333333",
        "#808080",
        "#cccccc",
        "#D33115",
        "#E27300",
        "#FCC400",
        "#000000",
        "#666666",
        "#B3B3B3",
        "#9F0500",
        "#C45100",
        "#FB9E00",
        "#DBDF00",
        "#A4DD00",
        "#68CCCA",
        "#73D8FF",
        "#AEA1FF",
        "#FDA1FF",
        "#B0BC00",
        "#68BC00",
        "#16A5A5",
        "#009CE0",
        "#7B64FF",
        "#FA28FF",
        "#808900",
        "#194D33",
        "#0C797D",
        "#0062B1",
        "#653294",
        "#AB149E",
    ],
    HEX_TRANSPARENCY: {
        100: "FF",
        99: "FC",
        98: "FA",
        97: "F7",
        96: "F5",
        95: "F2",
        94: "F0",
        93: "ED",
        92: "EB",
        91: "E8",
        90: "E6",
        89: "E3",
        88: "E0",
        87: "DE",
        86: "DB",
        85: "D9",
        84: "D6",
        83: "D4",
        82: "D1",
        81: "CF",
        80: "CC",
        79: "C9",
        78: "C7",
        77: "C4",
        76: "C2",
        75: "BF",
        74: "BD",
        73: "BA",
        72: "B8",
        71: "B5",
        70: "B3",
        69: "B0",
        68: "AD",
        67: "AB",
        66: "A8",
        65: "A6",
        64: "A3",
        63: "A1",
        62: "9E",
        61: "9C",
        60: "99",
        59: "96",
        58: "94",
        57: "91",
        56: "8F",
        55: "8C",
        54: "8A",
        53: "87",
        52: "85",
        51: "82",
        50: "80",
        49: "7D",
        48: "7A",
        47: "78",
        46: "75",
        45: "73",
        44: "70",
        43: "6E",
        42: "6B",
        41: "69",
        40: "66",
        39: "63",
        38: "61",
        37: "5E",
        36: "5C",
        35: "59",
        34: "57",
        33: "54",
        32: "52",
        31: "4F",
        30: "4D",
        29: "4A",
        28: "47",
        27: "45",
        26: "42",
        25: "40",
        24: "3D",
        23: "3B",
        22: "38",
        21: "36",
        20: "33",
        19: "30",
        18: "2E",
        17: "2B",
        16: "29",
        15: "26",
        14: "24",
        13: "21",
        12: "1F",
        11: "1C",
        10: "1A",
        9: "17",
        8: "14",
        7: "12",
        6: "0F",
        5: "0D",
        4: "0A",
        3: "08",
        2: "05",
        1: "03",
        0: "00",
    },
};
