from typing import List, Dict
import pydash

# Blue
from blue.memory.redis_memory_store import RedisMemoryStore
from blue.memory.in_memory_store import InMemoryStore


###############
### Memory (Base)
#
class Memory:
    """
    Base class for Memory.
    Handles database connection and common storage patterns.
    """

    def __init__(self, prefix: str, properties: Dict = None, store=None):
        """
        Initialize the Memory.

        Parameters:
            prefix (str): The base prefix for all keys generated by this (e.g., 'PLATFORM:default').
            properties (dict): Configuration for default store if none provided.
        """
        self.prefix = prefix
        if store:
            self.store = store
        else:
            protocol = pydash.objects.get(properties, ['memory_store.protocol'], 'in-memory')
            if protocol == 'redis':
                self.store = RedisMemoryStore(properties)
            elif protocol == 'in-memory':
                self.store = InMemoryStore()

        self.store.initialize()

    def _get_scoped_key(self, scope: str, identifier: str) -> str:
        """
        Generates the Redis key based on the hierarchy.
        Pattern: {prefix}:MEMORY:{scope}:{identifier}
        """
        return f"{self.prefix}:MEMORY:{scope}:{identifier}"

    def _append_to_list(self, key: str, entry: Dict) -> bool:
        return self.store.append_to_list(key, entry)

    def _get_list(self, key: str) -> List[Dict]:
        return self.store.get_list(key)
