from typing import List, Dict, Optional
import pydash

# Blue
from blue.memory.memory_store import MemoryStore
from blue.memory.redis_memory_store import RedisMemoryStore
from blue.memory.in_memory_store import InMemoryStore


###############
### Memory (Base)
#
class Memory:
    """
    Base class for Memory.
    Handles key scoping and delegates storage operations to the abstract MemoryStore.
    """

    def __init__(self, prefix: str, properties: Dict = None, store: MemoryStore = None):
        """
        Initialize the Memory.

        Parameters:
            prefix (str): The base prefix for all keys generated by this (e.g., 'PLATFORM:default').
            properties (dict): Configuration for default store if none provided.
            store (MemoryStore): Explicitly provided store instance.
        """
        self.prefix = prefix

        if store:
            self.store = store
        else:
            # default to 'in-memory' if not specified, falling back safely if properties is None
            protocol = pydash.objects.get(properties, ['memory_store.protocol'], 'in-memory')
            if protocol == 'redis':
                self.store = RedisMemoryStore(properties)
            elif protocol == 'in-memory':
                self.store = InMemoryStore()
            else:
                raise Exception(f"Unknown memory store protocol: {protocol}")

        self.store.initialize()

    def _get_scoped_key(self, scope: str, identifier: str) -> str:
        """
        Generates the base identifier (key) based on the hierarchy.
        Pattern: {prefix}:MEMORY:{scope}:{identifier}
        """
        return f"{self.prefix}:MEMORY:{scope}:{identifier}"

    # list delegates
    def _append_to_list(self, key: str, entry: Dict) -> bool:
        return self.store.append_to_list(key, entry)

    def _get_list(self, key: str) -> List[Dict]:
        return self.store.get_list(key)

    # indexed delegates
    def _store_indexed_entry(self, base_key: str, entry_id: str, entry: Dict, custom_key: Optional[str], timestamp: float) -> bool:
        """
        Delegate atomic storage of data and indices.
        """
        return self.store.store_indexed_entry(base_key, entry_id, entry, custom_key, timestamp)

    def _get_entry_by_id(self, base_key: str, entry_id: str) -> Optional[Dict]:
        """Delegate direct ID lookup."""
        return self.store.get_entry_by_id(base_key, entry_id)

    def _get_entry_by_key_index(self, base_key: str, custom_key: str) -> Optional[Dict]:
        """Delegate custom key lookup."""
        return self.store.get_entry_by_key_index(base_key, custom_key)

    def _get_entries_by_time_range(self, base_key: str, start: float, end: float) -> List[Dict]:
        """Delegate time range lookup."""
        return self.store.get_entries_by_time_range(base_key, start, end)
