from typing import List, Dict

# Blue
from blue.connection import PooledConnectionFactory


###############
### Memory (Base)
#
class Memory:
    """
    Base class for Memory.
    Handles database connection and common storage patterns.
    """

    def __init__(self, properties: Dict, prefix: str):
        """
        Initialize the Memory.

        Parameters:
            properties (dict): Configuration dictionary containing 'db.host', 'db.port', etc.
            prefix (str): The base prefix for all keys generated by this (e.g., 'PLATFORM:default').
        """
        self.properties = properties
        self.prefix = prefix

        # Initialize connection using the factory pattern
        self.connection_factory = PooledConnectionFactory(properties=self.properties)
        self.connection = self.connection_factory.get_connection()

    def _get_scoped_key(self, scope: str, identifier: str) -> str:
        """
        Generates the Redis key based on the hierarchy.
        Pattern: {prefix}:MEMORY:{scope}:{identifier}
        """
        return f"{self.prefix}:MEMORY:{scope}:{identifier}"

    def _append_to_list(self, redis_key: str, entry: Dict) -> bool:
        """Generic method to append an entry to a JSON list at the Redis key."""
        try:
            # Ensure the key exists as a list
            self.connection.json().set(redis_key, "$", [], nx=True)
            # Append entry
            self.connection.json().arrappend(redis_key, "$", entry)
        except Exception as ex:
            raise ex

    def _get_list(self, redis_key: str) -> List[Dict]:
        """Generic method to retrieve the full list from a Redis key."""
        if not self.connection.exists(redis_key):
            return []
        try:
            data = self.connection.json().get(redis_key)
            return data if data else []
        except Exception as ex:
            raise ex
