FROM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir huggingface-hub==0.25.1
RUN pip install -r requirements.txt

# Copy libs 
ADD /lib /app/lib/

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "summarizer_agent.py"]
