FROM --platform=$BUILDPLATFORM python:3.9
ARG BLUE_BUILD_CACHE_ARG
ARG BLUE_BUILD_LIB_ARG

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.core /app/requirements.core
RUN pip install ${BLUE_BUILD_CACHE_ARG} ${BLUE_BUILD_LIB_ARG} -r requirements.core

ADD src/requirements.service /app/requirements.service
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.service

ADD src/requirements.openai /app/requirements.openai
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.openai

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "openai_service.py" ] 
