FROM --platform=$BUILDPLATFORM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.core /app/requirements.core
RUN pip install --no-cache --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.core

ADD src/requirements.agent /app/requirements.agent
RUN pip install --no-cache -r requirements.agent

ADD src/requirements.recorder /app/requirements.recorder
RUN pip install --no-cache -r requirements.recorder

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "recorder.py"]
