FROM python:3.9

# Set workdir
WORKDIR /app

# Update pip
RUN pip install --upgrade pip

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copy libs 
ADD /lib /app/lib/

# Copy service files
ADD /src /app/

# Environment variables
ENV parameters '--list'

CMD ["sh", "-c", "python agent_registry.py ${parameters}"]
