FROM python:3.12

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copy libs 
ADD /lib /app/lib/

# Copy service files
ADD /src /app/
ADD /data /app/

ENTRYPOINT ["python", "prompt_optimizer_agent.py"]
