import { Colors } from "@blueprintjs/core";
import {
    faArrowRightFromArc,
    faArrowRightToArc,
    faCircleA,
    faCircleNodes,
    faCube,
    faDatabase,
    faFile,
    faFolderOpen,
    faFunction,
    faServer,
    faUsersViewfinder,
} from "@fortawesome/sharp-duotone-solid-svg-icons";
export const USER_ROLES_LOOKUP = {
        administrator: { text: "Administrator" },
        member: { text: "Member" },
        guest: { text: "Guest" },
        developer: { text: "Developer" },
        demo: { text: "Demo" },
    },
    MAIN_INFO_STYLES = {
        height: 40,
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        maxWidth: "100%",
    },
    ENTITY_TYPE_LOOKUP = {
        agent: { icon: faCircleA },
        data: { icon: faServer },
        agent_group: { icon: faUsersViewfinder },
        input: { icon: faArrowRightToArc },
        output: { icon: faArrowRightFromArc },
        source: { icon: faServer },
        database: { icon: faDatabase },
        collection: { icon: faFolderOpen },
        entity: { icon: faFile },
        relation: { icon: faCircleNodes },
        model: { icon: faCube },
        operator: { icon: faFunction },
    },
    DOCKER_CONTAINER_STATUS_LOOKUP = {
        created: { style: { color: Colors.ORANGE3 } },
        running: { style: { color: Colors.GREEN3 } },
        paused: { style: { color: Colors.RED3 } },
        restarting: { style: { color: Colors.ORANGE3 } },
        exited: { style: { color: Colors.RED3 } },
        removing: { style: { color: Colors.RED3 } },
        dead: { style: { color: Colors.RED3 } },
    },
    MIN_ALLOTMENT_PANE_SIZE = 400,
    MESSAGE_OVERFLOW_THRESHOLD = 200,
    WORKSAPCE_DRAGGABLE_SYMBOL = Symbol("workspaceDraggable"),
    POPPER_BOTTOM_WITH_MODIFIER_OVERFLOW_10 = {
        placement: "bottom",
        modifiers: {
            preventOverflow: {
                enabled: true,
                options: { padding: 10 },
            },
        },
    },
    ENTITY_MAIN_INFO_PROPERTY_KEYS = [
        "system_agent",
        "image",
        "display_name",
        "listens",
        "tags",
        "categories",
    ],
    REGISTRY_ENTITY_ICON_WRAPPER_STYLES = {
        height: 40,
        width: 40,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: Colors.WHITE,
    },
    EMPTY_ARRAY = [],
    HEX_TRANSPARENCY = {
        100: "FF",
        99: "FC",
        98: "FA",
        97: "F7",
        96: "F5",
        95: "F2",
        94: "F0",
        93: "ED",
        92: "EB",
        91: "E8",
        90: "E6",
        89: "E3",
        88: "E0",
        87: "DE",
        86: "DB",
        85: "D9",
        84: "D6",
        83: "D4",
        82: "D1",
        81: "CF",
        80: "CC",
        79: "C9",
        78: "C7",
        77: "C4",
        76: "C2",
        75: "BF",
        74: "BD",
        73: "BA",
        72: "B8",
        71: "B5",
        70: "B3",
        69: "B0",
        68: "AD",
        67: "AB",
        66: "A8",
        65: "A6",
        64: "A3",
        63: "A1",
        62: "9E",
        61: "9C",
        60: "99",
        59: "96",
        58: "94",
        57: "91",
        56: "8F",
        55: "8C",
        54: "8A",
        53: "87",
        52: "85",
        51: "82",
        50: "80",
        49: "7D",
        48: "7A",
        47: "78",
        46: "75",
        45: "73",
        44: "70",
        43: "6E",
        42: "6B",
        41: "69",
        40: "66",
        39: "63",
        38: "61",
        37: "5E",
        36: "5C",
        35: "59",
        34: "57",
        33: "54",
        32: "52",
        31: "4F",
        30: "4D",
        29: "4A",
        28: "47",
        27: "45",
        26: "42",
        25: "40",
        24: "3D",
        23: "3B",
        22: "38",
        21: "36",
        20: "33",
        19: "30",
        18: "2E",
        17: "2B",
        16: "29",
        15: "26",
        14: "24",
        13: "21",
        12: "1F",
        11: "1C",
        10: "1A",
        9: "17",
        8: "14",
        7: "12",
        6: "0F",
        5: "0D",
        4: "0A",
        3: "08",
        2: "05",
        1: "03",
        0: "00",
    };
