---
version: '3.8'
x-blue-common:
  &blue-common
  # build: .
  image: python:3.9.0
  environment:
    &blue-common-env
    BLUE_DEPLOY_PLATFORM: "${BLUE_DEPLOY_PLATFORM}"
    BLUE_DEPLOY_VERSION: "${BLUE_DEPLOY_VERSION}"
    BLUE_DEPLOY_TARGET: "${BLUE_DEPLOY_TARGET}"
    BLUE_PUBLIC_API_SERVER: "${BLUE_PUBLIC_API_SERVER}"
    BLUE_PUBLIC_API_SERVER_PORT: "${BLUE_PUBLIC_API_SERVER_PORT}"
    BLUE_PUBLIC_API_SERVER_PROTOCOL: "${BLUE_PUBLIC_API_SERVER_PROTOCOL}"
    BLUE_PUBLIC_WEB_SERVER: "${BLUE_PUBLIC_WEB_SERVER}"
    BLUE_PUBLIC_WEB_SERVER_PORT: "${BLUE_PUBLIC_WEB_SERVER_PORT}"
    BLUE_AGENT_REGISTRY: "${BLUE_AGENT_REGISTRY}"
    BLUE_DATA_REGISTRY: "${BLUE_DATA_REGISTRY}"
    BLUE_AGENT_REGISTRY_MODEL: "${BLUE_AGENT_REGISTRY_MODEL}"
  depends_on:
    &blue-common-depends-on
    redis:
      condition: service_healthy

services:
  ${AGENT_LOWERCASE}:
    image: ${IMAGE}
    hostname: blue_agent_${REGISTRY}_${AGENT}
    networks:
      - blue_platform_${BLUE_DEPLOY_PLATFORM}_network_bridge
    volumes:
      - blue_${BLUE_DEPLOY_PLATFORM}_data:/blue_data
    command: --serve ${AGENT} --properties '''${PROPERTIES}'''
    labels:
      blue.agent: "${BLUE_DEPLOY_PLATFORM}.${REGISTRY}.${AGENT}"
    environment:
      <<: *blue-common-env
    restart: always

networks:
  blue_platform_${BLUE_DEPLOY_PLATFORM}_network_bridge:
      external: true

volumes:
  blue_${BLUE_DEPLOY_PLATFORM}_data:
      external: true

