---
version: '3.8'
x-blue-common:
  &blue-common
  # build: .
  image: python:3.9.0
  environment:
    &blue-common-env
    BLUE__BACKEND__URL: redis://:@redis:6379/0
  volumes:
    - ${BLUE_INSTALL_DIR:-.}/data:/opt/blue/data
  user: "${BLUE_USER:-50000}:0"
  depends_on:
    &blue-common-depends-on
    redis:
      condition: service_healthy

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "8000:8000"
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    networks:
      - net
    environment:
      <<: *blue-common-env
    restart: always

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - ${BLUE_INSTALL_DIR:-.}postgres-data:/var/lib/postgresql/data
    environment:
      <<: *blue-common-env
      POSTGRES_PASSWORD: example
    restart: always

  neo4j:
    image: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    networks:
      - net
    volumes:
      - ${BLUE_INSTALL_DIR:-.}neo4j-data:/data
    environment:
      <<: *blue-common-env
    restart: always

  api:
    image: blue-platform-api
    ports:
      - "5050:5050"
    networks:
      - net
    environment:
      <<: *blue-common-env
    restart: always

networks:
  net:
      driver: bridge
