FROM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.core /app/requirements.core
RUN pip install --no-cache --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.core

ADD src/requirements.agent /app/requirements.agent
RUN pip install --no-cache -r requirements.agent

ADD src/requirements.data /app/requirements.data
RUN pip install --no-cache -r requirements.data

ADD src/requirements.registry /app/requirements.registry
RUN pip install --no-cache-dir --no-cache --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.registry

ADD src/requirements.query_executor /app/requirements.query_executor
RUN pip install --no-cache -r requirements.query_executor



# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "query_executor_agent.py"]
