FROM --platform=$BUILDPLATFORM python:3.10.12
ARG BLUE_BUILD_CACHE_ARG
ARG BLUE_BUILD_LIB_ARG
ARG BLUE_DEPLOY_VERSION
ENV BLUE_DEPLOY_VERSION=${BLUE_DEPLOY_VERSION}

# Set workdir
WORKDIR /app

# Install ping
RUN apt-get update
RUN apt-get install iputils-ping -y

# Update pip
RUN pip install --upgrade pip

# Add core requirements
ADD src/requirements.core /app/requirements.core
RUN pip install ${BLUE_BUILD_CACHE_ARG} ${BLUE_BUILD_LIB_ARG} -r requirements.core

ADD src/requirements.data /app/requirements.data
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.data

ADD src/requirements.registry /app/requirements.registry
RUN pip install ${BLUE_BUILD_CACHE_ARG} --no-cache-dir --no-cache --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.registry

ADD src/requirements.tool /app/requirements.tool
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.tool

# Add ray requirements
ADD src/requirements.ray /app/requirements.ray
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.ray

# Environment variables
ENV dashboard_host '0.0.0.0'
ENV port '6380'

CMD ["sh", "-c", "ray start --head --temp-dir=/blue_data/data/ray --enable-resource-isolation --system-reserved-memory=5368709120  --include-dashboard=False --disable-usage-stats --port ${port} --block"]

