FROM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
ADD src/requirements.common.txt /app/requirements.common.txt
# TBD: need to include the two json files to run the single-agent version
ADD src/demos.json /app/demos.json
ADD src/database_schema.json /app/database_schema.json

RUN pip install -r requirements.txt
RUN pip install -r requirements.common.txt

# Copy libs 
ADD /lib /app/lib/

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "magesql_agent.py"]
