---
version: '3.8'

services:
  websocket-service:
    image: blue-service-postgres
    ports:
      - "8004:8001"
    networks:
      - default
    env_file:
      - postgres.env
    restart: always


