from typing import List, Dict, Optional
import pydash

# Blue
from blue.memories.memory_store import MemoryStore
from blue.memories.redis_memory_store import RedisMemoryStore
from blue.memories.in_memory_store import InMemoryStore


###############
### Memory (Base)
#
class Memory:
    """
    Base class for Memory management.

    This class acts as a high-level facade for memory operations, handling key scoping
    (namespacing) and delegating the actual storage logic to an underlying
    `MemoryStore` implementation (e.g., Redis or In-Memory).

    Attributes:
        prefix (str): The global prefix used for all keys generated by this instance.
        store (MemoryStore): The backend storage implementation.
    """

    def __init__(self, prefix: str, properties: Dict = None, store: MemoryStore = None):
        """
        Initialize the Memory instance.

        Determines the backing store based on the provided `store` instance or the
        configuration found in `properties`.

        Parameters:
            prefix (str): The base prefix for all keys generated by this instance
                (e.g., 'PLATFORM:default').
            properties (Dict, optional): Configuration dictionary containing connection details
                and protocol preferences (e.g., `{'memory_store.protocol': 'redis'}`).
                Defaults to None.
            store (MemoryStore, optional): An explicit, pre-initialized MemoryStore instance.
                If provided, `properties` are ignored for store initialization.

        Raises:
            Exception: If the 'memory_store.protocol' in `properties` is unknown or unsupported.
        """
        self.prefix = prefix

        if store:
            self.store = store
        else:
            # default to 'in-memory' if not specified, falling back safely if properties is None
            protocol = pydash.objects.get(properties, ['memory_store.protocol'], 'in-memory')
            if protocol == 'redis':
                self.store = RedisMemoryStore(properties)
            elif protocol == 'in-memory':
                self.store = InMemoryStore()
            else:
                raise Exception(f"Unknown memory store protocol: {protocol}")

        self.store.initialize()

    def _get_scoped_key(self, scope: str, identifier: str) -> str:
        """
        Generates a fully namespaced identifier (key) based on the hierarchy.

        The resulting key follows the pattern: `{prefix}:MEMORY:{scope}:{identifier}`.

        Parameters:
            scope (str): The logical scope of the memory (e.g., 'agent', 'session').
            identifier (str): The specific ID within that scope.

        Returns:
            str: The fully qualified key string.
        """
        return f"{self.prefix}:MEMORY:{scope}:{identifier}"

    # list delegates
    def _append_to_list(self, key: str, entry: Dict) -> bool:
        """
        Appends a dictionary entry to a list at the specified key.

        Delegates to the underlying `MemoryStore`.

        Parameters:
            key (str): The fully qualified key of the list.
            entry (Dict): The data to append.

        Returns:
            bool: True if the operation was successful, False otherwise.
        """
        return self.store.append_to_list(key, entry)

    def _get_list(self, key: str) -> List[Dict]:
        """
        Retrieves the entire list stored at the specified key.

        Delegates to the underlying `MemoryStore`.

        Args:
            key (str): The fully qualified key of the list.

        Returns:
            List[Dict]: The list of stored entries, or an empty list if not found.
        """
        return self.store.get_list(key)

    # indexed delegates
    def _store_indexed_entry(self, base_key: str, entry_id: str, entry: Dict, custom_key: Optional[str], timestamp: float) -> bool:
        """
        Atomically stores an entry and updates associated indices.

        Delegates to the underlying `MemoryStore`. This usually handles:
        1. Storing the actual data.
        2. Updating a secondary index for `custom_key` lookups.
        3. Updating a sorted set for time-range lookups.

        Args:
            base_key (str): The base key for the collection.
            entry_id (str): Unique ID for the specific entry.
            entry (Dict): The data payload to store.
            custom_key (Optional[str]): A secondary lookup key (e.g., a tag or label).
            timestamp (float): The timestamp associated with the entry (for time-range sorting).

        Returns:
            bool: True if the operation was successful, False otherwise.
        """
        return self.store.store_indexed_entry(base_key, entry_id, entry, custom_key, timestamp)

    def _get_entry_by_id(self, base_key: str, entry_id: str) -> Optional[Dict]:
        """
        Retrieves a specific entry by its unique ID.

        Delegates to the underlying `MemoryStore`.

        Args:
            base_key (str): The base key for the collection.
            entry_id (str): The unique ID of the entry.

        Returns:
            Optional[Dict]: The entry data if found, None otherwise.
        """
        return self.store.get_entry_by_id(base_key, entry_id)

    def _get_entry_by_key_index(self, base_key: str, custom_key: str) -> Optional[Dict]:
        """
        Retrieves a specific entry using a secondary custom key (index).

        Delegates to the underlying `MemoryStore`.

        Args:
            base_key (str): The base key for the collection.
            custom_key (str): The secondary lookup key.

        Returns:
            Optional[Dict]: The entry data if found, None otherwise.
        """
        return self.store.get_entry_by_key_index(base_key, custom_key)

    def _get_entries_by_time_range(self, base_key: str, start: float, end: float) -> List[Dict]:
        """
        Retrieves a list of entries falling within a specific time range.

        Delegates to the underlying `MemoryStore`.

        Args:
            base_key (str): The base key for the collection.
            start (float): The start timestamp (inclusive).
            end (float): The end timestamp (inclusive).

        Returns:
            List[Dict]: A list of entries found within the range.
        """
        return self.store.get_entries_by_time_range(base_key, start, end)
