FROM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
ADD lib/data_registry/requirements.txt /app/requirements_data_registry.txt
RUN pip install --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.txt
RUN pip install --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements_data_registry.txt



# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "knowledge_grounding_agent.py"]
