site_name: Blue Docs
repo_url: https://github.com/megagonlabs/blue
theme:
    name: material
    logo: assets/logo.svg
    favicon: assets/favicon.ico
    custom_dir: overrides
    features:
        - navigation.instant
        - search.highlight
        - search.suggest
    icon:
        admonition:
            example: fontawesome/solid/laptop-code
        repo: fontawesome/brands/github
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: fontawesome/solid/laptop
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: custom
          accent: custom
          toggle:
              icon: fontawesome/solid/sun
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          accent: custom
          toggle:
              icon: fontawesome/solid/moon
              name: Switch to system preference
watch:
    - ../lib/src/blue
plugins:
    - offline
    - search
    - macros
    - git-revision-date-localized:
          type: timeago
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  options:
                      docstring_style: google
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
    - stylesheets/extra.css
extra:
    canonical_version: v1.0
    version:
        provider: mike
        alias: true
    social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/megagon-labs
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/MegagonLabs
        - icon: fontawesome/brands/facebook
          link: https://www.facebook.com/megagonlabs/
