FROM --platform=$BUILDPLATFORM python:3.9
ARG BLUE_BUILD_CACHE_ARG
ARG BLUE_BUILD_LIB_ARG

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.core /app/requirements.core
RUN pip install ${BLUE_BUILD_CACHE_ARG} ${BLUE_BUILD_LIB_ARG} -r requirements.core

ADD src/requirements.agent /app/requirements.agent
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.agent

ADD src/requirements.data /app/requirements.data
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.data

ADD src/requirements.registry /app/requirements.registry
RUN pip install ${BLUE_BUILD_CACHE_ARG} --no-cache-dir --no-cache --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.registry

ADD src/requirements.requestor /app/requirements.requestor
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.requestor

ADD src/requirements.openai /app/requirements.openai
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.openai

ADD src/requirements.nl2sql /app/requirements.nl2sql
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.nl2sql



# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "nl2sql_agent.py"]
