FROM python:3.9

# Set workdir
WORKDIR /app

# This is a hack to avoid huge docker image by installing sentence-transformers with CPU-only pytorch first
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir transformers tqdm numpy scikit-learn scipy nltk sentencepiece
RUN pip install --no-cache-dir --no-deps sentence-transformers==2.2.2

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
RUN pip install --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.txt

ADD src/requirements.common.txt /app/requirements.common.txt
RUN pip install --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.common.txt

ADD src/requirements.data_registry.txt /app/requirements.data_registry.txt
RUN pip install --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.data_registry.txt



# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "nl2sql_agent.py"]
